export const ProblemCodes = {
  SNAP_NOT_OWNED: 'SNAP_NOT_OWNED',
  SNAP_ALREADY_IN_AREA: 'SNAP_ALREADY_IN_AREA',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  DUPLICATE_REPORT: 'DUPLICATE_REPORT',
  ACCOUNT_DELETE_INCOMPLETE: 'ACCOUNT_DELETE_INCOMPLETE',
  PASSWORD_RESET_INVALID: 'PASSWORD_RESET_INVALID',
} as const;
