// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.21.12
// source: proto/storage.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "storage";

export interface GetSignedURLDTO {
  key: string;
  expiresIn: number;
}

export interface GetSignedURLReturn {
  url: string;
}

export const STORAGE_PACKAGE_NAME = "storage";

function createBaseGetSignedURLDTO(): GetSignedURLDTO {
  return { key: "", expiresIn: 0 };
}

export const GetSignedURLDTO: MessageFns<GetSignedURLDTO> = {
  encode(message: GetSignedURLDTO, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.expiresIn !== 0) {
      writer.uint32(16).int32(message.expiresIn);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSignedURLDTO {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSignedURLDTO();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.expiresIn = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetSignedURLReturn(): GetSignedURLReturn {
  return { url: "" };
}

export const GetSignedURLReturn: MessageFns<GetSignedURLReturn> = {
  encode(message: GetSignedURLReturn, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.url !== "") {
      writer.uint32(10).string(message.url);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSignedURLReturn {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSignedURLReturn();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.url = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface AwsStorageClient {
  getSignedUrlForFile(request: GetSignedURLDTO): Observable<GetSignedURLReturn>;
}

export interface AwsStorageController {
  getSignedUrlForFile(
    request: GetSignedURLDTO,
  ): Promise<GetSignedURLReturn> | Observable<GetSignedURLReturn> | GetSignedURLReturn;
}

export function AwsStorageControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getSignedUrlForFile"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AwsStorage", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AwsStorage", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AWS_STORAGE_SERVICE_NAME = "AwsStorage";

export type AwsStorageService = typeof AwsStorageService;
export const AwsStorageService = {
  getSignedUrlForFile: {
    path: "/storage.AwsStorage/getSignedUrlForFile",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetSignedURLDTO): Buffer => Buffer.from(GetSignedURLDTO.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetSignedURLDTO => GetSignedURLDTO.decode(value),
    responseSerialize: (value: GetSignedURLReturn): Buffer => Buffer.from(GetSignedURLReturn.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetSignedURLReturn => GetSignedURLReturn.decode(value),
  },
} as const;

export interface AwsStorageServer extends UntypedServiceImplementation {
  getSignedUrlForFile: handleUnaryCall<GetSignedURLDTO, GetSignedURLReturn>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
