apiVersion: v1
kind: Secret
metadata:
  name: nowhere-snaps-secrets
type: Opaque
stringData:
  ACCESS_SECRET: change_me_jwt_access_secret
  NATS_URL: nats://change_me_nats_token@nats:4222
  GATEWAY_URL: https://app.example.com
  CORS_ORIGIN: https://app.example.com
  NODE_ENV: production
  ENABLE_SEED: 'false'
  NEST_PORT: '3000'
  MAX_DISTANCE_NEAR: '5000'
  MIN_DISTANCE_SAME_USER: '500'
  SNAP_DISAPPEAR_TIME: '1'
