apiVersion: v1
kind: Secret
metadata:
  name: nowhere-storage-s3-secrets
type: Opaque
stringData:
  STORAGE_PROVIDER: aws
  AWS_BUCKET: change_me_bucket
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: change_me_access_key_id
  AWS_SECRET_ACCESS_KEY: change_me_secret_access_key
  AWS_ENDPOINT_URL: ''
