apiVersion: v1
kind: Secret
metadata:
  name: nowhere-users-db-secrets
type: Opaque
stringData:
  MYSQL_HOST: mysql
  MYSQL_PORT: '3306'
  MYSQL_DATABASE: Users_Info
  MYSQL_USER: info_admin
  MYSQL_PASS: change_me_mysql_pass
  NATS_URL: nats://change_me_nats_token@nats:4222
  NODE_ENV: production
  TYPEORM_SYNC: 'false'
  NEST_PORT: '3001'
