apiVersion: v1
kind: Secret
metadata:
  name: nowhere-gateway-secrets
type: Opaque
stringData:
  ACCESS_SECRET: change_me_jwt_access_secret
  NATS_URL: nats://change_me_nats_token@nats:4222
  CORS_ORIGIN: https://app.example.com
  NODE_ENV: production
  PORT: '3005'
