apiVersion: v1
kind: Secret
metadata:
  name: nowhere-mongo-secrets
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: change_me_mongo_root_pass
  MONGO_INITDB_DATABASE: snaps
