apiVersion: v1
kind: Secret
metadata:
  name: nowhere-storage-redis-secrets
type: Opaque
stringData:
  REDIS_URL: redis://:change_me_redis_password@redis:6379
  CACHE_TTL: '86340'
  NATS_URL: nats://change_me_nats_token@nats:4222
  NODE_ENV: production
  NEST_PORT: '3002'
