apiVersion: v1
kind: Secret
metadata:
  name: nowhere-auth-token-secrets
type: Opaque
stringData:
  ACCESS_SECRET: change_me_jwt_access_secret
  REFRESH_SECRET: change_me_jwt_refresh_secret
  ACCESS_EXP: 15m
  REFRESH_EXP: 7d
  ADMIN_EMAIL: admin@example.com
  ADMIN_PASSWORD: change_me_admin_password
