// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.21.12
// source: authentication.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Timestamp } from "./google/protobuf/timestamp";

export enum AuthUserRole {
  ADMIN = 0,
  USER = 1,
  UNRECOGNIZED = -1,
}

export interface AuthUser {
  Id: string;
  password: string;
  email: string;
  isActive: boolean;
  role: string;
  lastLoginAt: Timestamp | undefined;
}

export interface ValidateUserAuthDto {
  email: string;
  password: string;
}

export interface ValidateTokenAuthDto {
  token: string;
}

function createBaseAuthUser(): AuthUser {
  return { Id: "", password: "", email: "", isActive: false, role: "", lastLoginAt: undefined };
}

export const AuthUser: MessageFns<AuthUser> = {
  encode(message: AuthUser, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.Id !== "") {
      writer.uint32(10).string(message.Id);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    if (message.email !== "") {
      writer.uint32(26).string(message.email);
    }
    if (message.isActive !== false) {
      writer.uint32(32).bool(message.isActive);
    }
    if (message.role !== "") {
      writer.uint32(42).string(message.role);
    }
    if (message.lastLoginAt !== undefined) {
      Timestamp.encode(message.lastLoginAt, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthUser {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthUser();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.Id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.isActive = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.role = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.lastLoginAt = Timestamp.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseValidateUserAuthDto(): ValidateUserAuthDto {
  return { email: "", password: "" };
}

export const ValidateUserAuthDto: MessageFns<ValidateUserAuthDto> = {
  encode(message: ValidateUserAuthDto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateUserAuthDto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateUserAuthDto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseValidateTokenAuthDto(): ValidateTokenAuthDto {
  return { token: "" };
}

export const ValidateTokenAuthDto: MessageFns<ValidateTokenAuthDto> = {
  encode(message: ValidateTokenAuthDto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateTokenAuthDto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateTokenAuthDto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface CredentialsClient {
  validateAuthUser(request: ValidateUserAuthDto): Observable<AuthUser>;

  validateAuthToken(request: ValidateTokenAuthDto): Observable<AuthUser>;
}

export interface CredentialsController {
  validateAuthUser(request: ValidateUserAuthDto): Promise<AuthUser> | Observable<AuthUser> | AuthUser;

  validateAuthToken(request: ValidateTokenAuthDto): Promise<AuthUser> | Observable<AuthUser> | AuthUser;
}

export function CredentialsControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["validateAuthUser", "validateAuthToken"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Credentials", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Credentials", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CREDENTIALS_SERVICE_NAME = "Credentials";

export type CredentialsService = typeof CredentialsService;
export const CredentialsService = {
  validateAuthUser: {
    path: "/Credentials.Credentials/validateAuthUser",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ValidateUserAuthDto): Buffer => Buffer.from(ValidateUserAuthDto.encode(value).finish()),
    requestDeserialize: (value: Buffer): ValidateUserAuthDto => ValidateUserAuthDto.decode(value),
    responseSerialize: (value: AuthUser): Buffer => Buffer.from(AuthUser.encode(value).finish()),
    responseDeserialize: (value: Buffer): AuthUser => AuthUser.decode(value),
  },
  validateAuthToken: {
    path: "/Credentials.Credentials/validateAuthToken",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ValidateTokenAuthDto): Buffer => Buffer.from(ValidateTokenAuthDto.encode(value).finish()),
    requestDeserialize: (value: Buffer): ValidateTokenAuthDto => ValidateTokenAuthDto.decode(value),
    responseSerialize: (value: AuthUser): Buffer => Buffer.from(AuthUser.encode(value).finish()),
    responseDeserialize: (value: Buffer): AuthUser => AuthUser.decode(value),
  },
} as const;

export interface CredentialsServer extends UntypedServiceImplementation {
  validateAuthUser: handleUnaryCall<ValidateUserAuthDto, AuthUser>;
  validateAuthToken: handleUnaryCall<ValidateTokenAuthDto, AuthUser>;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
