// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.21.12
// source: auth-user.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export enum UserRole {
  ADMIN = 0,
  USER = 1,
  UNRECOGNIZED = -1,
}

export interface Users {
  users: User[];
}

export interface Empty {
}

export interface CreateUserDTO {
  password: string;
  email: string;
  bio: string;
  firstName: string;
  lastName: string;
  role: UserRole;
}

export interface Settings {
  id: string;
  user: User | undefined;
  maxDistance: number;
  newSnapDistance: number;
  snapDisappearTime: number;
}

export interface GetUserSettingsDTO {
  id: string;
}

export interface User {
  Id: string;
  password: string;
  email: string;
  firstName: string;
  lastName: string;
  bio: string;
  isActive: boolean;
  role: string;
  image: string;
}

export interface ValidateUserDto {
  email: string;
  password: string;
}

export interface ValidateTokenDto {
  token: string;
}

function createBaseUsers(): Users {
  return { users: [] };
}

export const Users: MessageFns<Users> = {
  encode(message: Users, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.users) {
      User.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Users {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUsers();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.users.push(User.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseEmpty(): Empty {
  return {};
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCreateUserDTO(): CreateUserDTO {
  return { password: "", email: "", bio: "", firstName: "", lastName: "", role: 0 };
}

export const CreateUserDTO: MessageFns<CreateUserDTO> = {
  encode(message: CreateUserDTO, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.password !== "") {
      writer.uint32(10).string(message.password);
    }
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    if (message.bio !== "") {
      writer.uint32(26).string(message.bio);
    }
    if (message.firstName !== "") {
      writer.uint32(34).string(message.firstName);
    }
    if (message.lastName !== "") {
      writer.uint32(42).string(message.lastName);
    }
    if (message.role !== 0) {
      writer.uint32(48).int32(message.role);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateUserDTO {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateUserDTO();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.bio = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.firstName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.lastName = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseSettings(): Settings {
  return { id: "", user: undefined, maxDistance: 0, newSnapDistance: 0, snapDisappearTime: 0 };
}

export const Settings: MessageFns<Settings> = {
  encode(message: Settings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.user !== undefined) {
      User.encode(message.user, writer.uint32(18).fork()).join();
    }
    if (message.maxDistance !== 0) {
      writer.uint32(24).int32(message.maxDistance);
    }
    if (message.newSnapDistance !== 0) {
      writer.uint32(32).int32(message.newSnapDistance);
    }
    if (message.snapDisappearTime !== 0) {
      writer.uint32(40).int32(message.snapDisappearTime);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Settings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user = User.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.maxDistance = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.newSnapDistance = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.snapDisappearTime = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUserSettingsDTO(): GetUserSettingsDTO {
  return { id: "" };
}

export const GetUserSettingsDTO: MessageFns<GetUserSettingsDTO> = {
  encode(message: GetUserSettingsDTO, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserSettingsDTO {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserSettingsDTO();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUser(): User {
  return {
    Id: "",
    password: "",
    email: "",
    firstName: "",
    lastName: "",
    bio: "",
    isActive: false,
    role: "",
    image: "",
  };
}

export const User: MessageFns<User> = {
  encode(message: User, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.Id !== "") {
      writer.uint32(10).string(message.Id);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    if (message.email !== "") {
      writer.uint32(26).string(message.email);
    }
    if (message.firstName !== "") {
      writer.uint32(34).string(message.firstName);
    }
    if (message.lastName !== "") {
      writer.uint32(42).string(message.lastName);
    }
    if (message.bio !== "") {
      writer.uint32(50).string(message.bio);
    }
    if (message.isActive !== false) {
      writer.uint32(56).bool(message.isActive);
    }
    if (message.role !== "") {
      writer.uint32(66).string(message.role);
    }
    if (message.image !== "") {
      writer.uint32(74).string(message.image);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): User {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUser();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.Id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.firstName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.lastName = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.bio = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.isActive = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.role = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.image = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseValidateUserDto(): ValidateUserDto {
  return { email: "", password: "" };
}

export const ValidateUserDto: MessageFns<ValidateUserDto> = {
  encode(message: ValidateUserDto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateUserDto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateUserDto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseValidateTokenDto(): ValidateTokenDto {
  return { token: "" };
}

export const ValidateTokenDto: MessageFns<ValidateTokenDto> = {
  encode(message: ValidateTokenDto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateTokenDto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateTokenDto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface AuthUsersClient {
  validateUser(request: ValidateUserDto): Observable<User>;

  validateToken(request: ValidateTokenDto): Observable<User>;

  /** user settings */

  getUserSetting(request: GetUserSettingsDTO): Observable<Settings>;

  createUser(request: CreateUserDTO): Observable<User>;

  getAllUsers(request: Empty): Observable<Users>;
}

export interface AuthUsersController {
  validateUser(request: ValidateUserDto): Promise<User> | Observable<User> | User;

  validateToken(request: ValidateTokenDto): Promise<User> | Observable<User> | User;

  /** user settings */

  getUserSetting(request: GetUserSettingsDTO): Promise<Settings> | Observable<Settings> | Settings;

  createUser(request: CreateUserDTO): Promise<User> | Observable<User> | User;

  getAllUsers(request: Empty): Promise<Users> | Observable<Users> | Users;
}

export function AuthUsersControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["validateUser", "validateToken", "getUserSetting", "createUser", "getAllUsers"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthUsers", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthUsers", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_USERS_SERVICE_NAME = "AuthUsers";

export type AuthUsersService = typeof AuthUsersService;
export const AuthUsersService = {
  validateUser: {
    path: "/auth.AuthUsers/validateUser",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ValidateUserDto): Buffer => Buffer.from(ValidateUserDto.encode(value).finish()),
    requestDeserialize: (value: Buffer): ValidateUserDto => ValidateUserDto.decode(value),
    responseSerialize: (value: User): Buffer => Buffer.from(User.encode(value).finish()),
    responseDeserialize: (value: Buffer): User => User.decode(value),
  },
  validateToken: {
    path: "/auth.AuthUsers/validateToken",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ValidateTokenDto): Buffer => Buffer.from(ValidateTokenDto.encode(value).finish()),
    requestDeserialize: (value: Buffer): ValidateTokenDto => ValidateTokenDto.decode(value),
    responseSerialize: (value: User): Buffer => Buffer.from(User.encode(value).finish()),
    responseDeserialize: (value: Buffer): User => User.decode(value),
  },
  /** user settings */
  getUserSetting: {
    path: "/auth.AuthUsers/getUserSetting",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetUserSettingsDTO): Buffer => Buffer.from(GetUserSettingsDTO.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUserSettingsDTO => GetUserSettingsDTO.decode(value),
    responseSerialize: (value: Settings): Buffer => Buffer.from(Settings.encode(value).finish()),
    responseDeserialize: (value: Buffer): Settings => Settings.decode(value),
  },
  createUser: {
    path: "/auth.AuthUsers/createUser",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateUserDTO): Buffer => Buffer.from(CreateUserDTO.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateUserDTO => CreateUserDTO.decode(value),
    responseSerialize: (value: User): Buffer => Buffer.from(User.encode(value).finish()),
    responseDeserialize: (value: Buffer): User => User.decode(value),
  },
  getAllUsers: {
    path: "/auth.AuthUsers/getAllUsers",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    requestDeserialize: (value: Buffer): Empty => Empty.decode(value),
    responseSerialize: (value: Users): Buffer => Buffer.from(Users.encode(value).finish()),
    responseDeserialize: (value: Buffer): Users => Users.decode(value),
  },
} as const;

export interface AuthUsersServer extends UntypedServiceImplementation {
  validateUser: handleUnaryCall<ValidateUserDto, User>;
  validateToken: handleUnaryCall<ValidateTokenDto, User>;
  /** user settings */
  getUserSetting: handleUnaryCall<GetUserSettingsDTO, Settings>;
  createUser: handleUnaryCall<CreateUserDTO, User>;
  getAllUsers: handleUnaryCall<Empty, Users>;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
