// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.21.12
// source: users.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export interface UserNotSeenObject {
  seen: boolean;
  userID: string;
  snapID?: string | undefined;
}

export interface UserSeenObject {
  snapID: string;
  userID: string;
}

export interface UserSeenObjects {
  seen: UserSeenObject[];
}

export interface UserSuccess {
  success: boolean;
}

export interface UsersObject {
  users: UserObject[];
}

export interface EmptyUserInfo {
}

export interface CreateUser {
  bio: string;
  /** this will save authentication information id for each user */
  authID: string;
  firstName: string;
  lastName: string;
}

export interface UserSetting {
  id: string;
  user: UserObject | undefined;
  maxDistance: number;
  newSnapDistance: number;
  snapDisappearTime: number;
}

export interface UserSettingFetchDTO {
  id: string;
}

export interface UserObject {
  Id: string;
  userID: string;
  firstName: string;
  lastName: string;
  bio: string;
  image: string;
}

function createBaseUserNotSeenObject(): UserNotSeenObject {
  return { seen: false, userID: "" };
}

export const UserNotSeenObject: MessageFns<UserNotSeenObject> = {
  encode(message: UserNotSeenObject, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.seen !== false) {
      writer.uint32(8).bool(message.seen);
    }
    if (message.userID !== "") {
      writer.uint32(18).string(message.userID);
    }
    if (message.snapID !== undefined) {
      writer.uint32(26).string(message.snapID);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserNotSeenObject {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserNotSeenObject();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.seen = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userID = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.snapID = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUserSeenObject(): UserSeenObject {
  return { snapID: "", userID: "" };
}

export const UserSeenObject: MessageFns<UserSeenObject> = {
  encode(message: UserSeenObject, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.snapID !== "") {
      writer.uint32(10).string(message.snapID);
    }
    if (message.userID !== "") {
      writer.uint32(18).string(message.userID);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserSeenObject {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserSeenObject();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.snapID = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userID = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUserSeenObjects(): UserSeenObjects {
  return { seen: [] };
}

export const UserSeenObjects: MessageFns<UserSeenObjects> = {
  encode(message: UserSeenObjects, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.seen) {
      UserSeenObject.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserSeenObjects {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserSeenObjects();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.seen.push(UserSeenObject.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUserSuccess(): UserSuccess {
  return { success: false };
}

export const UserSuccess: MessageFns<UserSuccess> = {
  encode(message: UserSuccess, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserSuccess {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserSuccess();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUsersObject(): UsersObject {
  return { users: [] };
}

export const UsersObject: MessageFns<UsersObject> = {
  encode(message: UsersObject, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.users) {
      UserObject.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UsersObject {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUsersObject();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.users.push(UserObject.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseEmptyUserInfo(): EmptyUserInfo {
  return {};
}

export const EmptyUserInfo: MessageFns<EmptyUserInfo> = {
  encode(_: EmptyUserInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmptyUserInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmptyUserInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCreateUser(): CreateUser {
  return { bio: "", authID: "", firstName: "", lastName: "" };
}

export const CreateUser: MessageFns<CreateUser> = {
  encode(message: CreateUser, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bio !== "") {
      writer.uint32(10).string(message.bio);
    }
    if (message.authID !== "") {
      writer.uint32(18).string(message.authID);
    }
    if (message.firstName !== "") {
      writer.uint32(26).string(message.firstName);
    }
    if (message.lastName !== "") {
      writer.uint32(34).string(message.lastName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateUser {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateUser();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.bio = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.authID = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.firstName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.lastName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUserSetting(): UserSetting {
  return { id: "", user: undefined, maxDistance: 0, newSnapDistance: 0, snapDisappearTime: 0 };
}

export const UserSetting: MessageFns<UserSetting> = {
  encode(message: UserSetting, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.user !== undefined) {
      UserObject.encode(message.user, writer.uint32(18).fork()).join();
    }
    if (message.maxDistance !== 0) {
      writer.uint32(24).int32(message.maxDistance);
    }
    if (message.newSnapDistance !== 0) {
      writer.uint32(32).int32(message.newSnapDistance);
    }
    if (message.snapDisappearTime !== 0) {
      writer.uint32(40).int32(message.snapDisappearTime);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserSetting {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserSetting();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user = UserObject.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.maxDistance = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.newSnapDistance = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.snapDisappearTime = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUserSettingFetchDTO(): UserSettingFetchDTO {
  return { id: "" };
}

export const UserSettingFetchDTO: MessageFns<UserSettingFetchDTO> = {
  encode(message: UserSettingFetchDTO, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserSettingFetchDTO {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserSettingFetchDTO();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUserObject(): UserObject {
  return { Id: "", userID: "", firstName: "", lastName: "", bio: "", image: "" };
}

export const UserObject: MessageFns<UserObject> = {
  encode(message: UserObject, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.Id !== "") {
      writer.uint32(10).string(message.Id);
    }
    if (message.userID !== "") {
      writer.uint32(18).string(message.userID);
    }
    if (message.firstName !== "") {
      writer.uint32(26).string(message.firstName);
    }
    if (message.lastName !== "") {
      writer.uint32(34).string(message.lastName);
    }
    if (message.bio !== "") {
      writer.uint32(42).string(message.bio);
    }
    if (message.image !== "") {
      writer.uint32(50).string(message.image);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserObject {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserObject();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.Id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userID = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.firstName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.lastName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.bio = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.image = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface UsersClient {
  getSettings(request: UserSettingFetchDTO): Observable<UserSetting>;

  createUserInfo(request: CreateUser): Observable<UserObject>;

  getAllUsersInfo(request: EmptyUserInfo): Observable<UsersObject>;

  setSeenSnap(request: UserSeenObject): Observable<UserSuccess>;

  notSeenSnaps(request: UserNotSeenObject): Observable<UserSeenObjects>;
}

export interface UsersController {
  getSettings(request: UserSettingFetchDTO): Promise<UserSetting> | Observable<UserSetting> | UserSetting;

  createUserInfo(request: CreateUser): Promise<UserObject> | Observable<UserObject> | UserObject;

  getAllUsersInfo(request: EmptyUserInfo): Promise<UsersObject> | Observable<UsersObject> | UsersObject;

  setSeenSnap(request: UserSeenObject): Promise<UserSuccess> | Observable<UserSuccess> | UserSuccess;

  notSeenSnaps(request: UserNotSeenObject): Promise<UserSeenObjects> | Observable<UserSeenObjects> | UserSeenObjects;
}

export function UsersControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getSettings", "createUserInfo", "getAllUsersInfo", "setSeenSnap", "notSeenSnaps"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Users", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Users", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USERS_SERVICE_NAME = "Users";

export type UsersService = typeof UsersService;
export const UsersService = {
  getSettings: {
    path: "/USERS.Users/getSettings",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UserSettingFetchDTO): Buffer => Buffer.from(UserSettingFetchDTO.encode(value).finish()),
    requestDeserialize: (value: Buffer): UserSettingFetchDTO => UserSettingFetchDTO.decode(value),
    responseSerialize: (value: UserSetting): Buffer => Buffer.from(UserSetting.encode(value).finish()),
    responseDeserialize: (value: Buffer): UserSetting => UserSetting.decode(value),
  },
  createUserInfo: {
    path: "/USERS.Users/CreateUserInfo",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateUser): Buffer => Buffer.from(CreateUser.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateUser => CreateUser.decode(value),
    responseSerialize: (value: UserObject): Buffer => Buffer.from(UserObject.encode(value).finish()),
    responseDeserialize: (value: Buffer): UserObject => UserObject.decode(value),
  },
  getAllUsersInfo: {
    path: "/USERS.Users/getAllUsersInfo",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: EmptyUserInfo): Buffer => Buffer.from(EmptyUserInfo.encode(value).finish()),
    requestDeserialize: (value: Buffer): EmptyUserInfo => EmptyUserInfo.decode(value),
    responseSerialize: (value: UsersObject): Buffer => Buffer.from(UsersObject.encode(value).finish()),
    responseDeserialize: (value: Buffer): UsersObject => UsersObject.decode(value),
  },
  setSeenSnap: {
    path: "/USERS.Users/setSeenSnap",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UserSeenObject): Buffer => Buffer.from(UserSeenObject.encode(value).finish()),
    requestDeserialize: (value: Buffer): UserSeenObject => UserSeenObject.decode(value),
    responseSerialize: (value: UserSuccess): Buffer => Buffer.from(UserSuccess.encode(value).finish()),
    responseDeserialize: (value: Buffer): UserSuccess => UserSuccess.decode(value),
  },
  notSeenSnaps: {
    path: "/USERS.Users/notSeenSnaps",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UserNotSeenObject): Buffer => Buffer.from(UserNotSeenObject.encode(value).finish()),
    requestDeserialize: (value: Buffer): UserNotSeenObject => UserNotSeenObject.decode(value),
    responseSerialize: (value: UserSeenObjects): Buffer => Buffer.from(UserSeenObjects.encode(value).finish()),
    responseDeserialize: (value: Buffer): UserSeenObjects => UserSeenObjects.decode(value),
  },
} as const;

export interface UsersServer extends UntypedServiceImplementation {
  getSettings: handleUnaryCall<UserSettingFetchDTO, UserSetting>;
  createUserInfo: handleUnaryCall<CreateUser, UserObject>;
  getAllUsersInfo: handleUnaryCall<EmptyUserInfo, UsersObject>;
  setSeenSnap: handleUnaryCall<UserSeenObject, UserSuccess>;
  notSeenSnaps: handleUnaryCall<UserNotSeenObject, UserSeenObjects>;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
